### ISSUE TITLE
Missing library - utils.survival_utils

### ISSUE THREAD

**Issue by BenPashley** [dddavid4real/HistGen#8]
Hello again,

I am unable to execute extract_features_fp.py as the following library appears to be missing?

Traceback (most recent call last):
  File "/root/HistGen/CLAM/extract_features_fp.py", line 10, in <module>
    from utils.utils import collate_features
  File "/root/HistGen/CLAM/utils/utils.py", line 18, in <module>
    from .survival_utils import collate_MIL_survival
ModuleNotFoundError: No module named 'utils.survival_utils'

**Comment by dddavid4real** [comment]
Hi! Thank you for reporting this error!

Have you already solved this one?
