### ISSUE TITLE
Checkpoint dinov2_cpath_v1.pth does not load?

### ISSUE THREAD

**Issue by BenPashley** [dddavid4real/HistGen#9]
Hi,

On attempting to extract the features for the pre-processed TCGA slides I get the following error when using your custom embedding weights. Is the checkpoint file corrupt?

initializing dataset
loading model checkpoint: dinov2_vitl
Device:cuda, GPU Count:1

Traceback (most recent call last):
  File "/root/HistGen/CLAM/extract_features_fp.py", line 154, in <module>
    model = get_model(args.model, device, torch.cuda.device_count())
  File "/root/HistGen/CLAM/models/__init__.py", line 73, in get_model
    model, _ = build_model(device, gpu_num, model_name, __implemented_models[model_name])
  File "/root/HistGen/CLAM/models/dinov2/__init__.py", line 20, in build_model
    ckpt = torch.load(ckpt_path)['teacher']
  File "/root/miniconda3/envs/clam_latest/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/clam_latest/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by dddavid4real** [comment]
Hi! Thank you for reporting this error!

Have you managed to solve it?

**Comment by BenPashley** [comment]
Hi! Thanks, yes it was due to a corrupt download.  Hopefully I can now move forward...  Thanks again for your help.
